import 'dart:async';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:vibration/vibration.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_text_styles.dart';
import '../../../core/services/firestore_service.dart';
import '../../../core/services/assignment_service.dart';
import '../../../core/models/incident_model.dart';
import 'package:provider/provider.dart';

class CountdownOverlay extends StatefulWidget {
  final String roomNumber;
  const CountdownOverlay({super.key, required this.roomNumber});

  @override
  _CountdownOverlayState createState() => _CountdownOverlayState();
}

class _CountdownOverlayState extends State<CountdownOverlay> with SingleTickerProviderStateMixin {
  int _counter = 5;
  Timer? _timer;
  late AnimationController _pulseController;
  bool _isCreating = false;

  @override
  void initState() {
    super.initState();
    _pulseController = AnimationController(vsync: this, duration: const Duration(milliseconds: 500))..repeat(reverse: true);
    _startTimer();
    _triggerVibration();
  }

  void _startTimer() {
    _timer = Timer.periodic(const Duration(seconds: 1), (timer) {
      if (_counter > 1) {
        setState(() {
          _counter--;
        });
        _triggerVibration();
      } else {
        _timer?.cancel();
        _sendAlert();
      }
    });
  }

  void _triggerVibration() async {
    if (await Vibration.hasVibrator() ?? false) {
      if (_counter > 2) {
        Vibration.vibrate(duration: 200);
      } else {
        Vibration.vibrate(duration: 500, amplitude: 255);
      }
    }
  }

  void _sendAlert() async {
    if (_isCreating) return;
    setState(() => _isCreating = true);
    
    _timer?.cancel(); // Ensure timer is stopped
    
    try {
      final firestore = Provider.of<FirestoreService>(context, listen: false);
      final assignment = AssignmentService();
      
      // Find closest staff (mock coordinates for demo)
      final closestId = await assignment.findClosestStaff('other', 28.6139, 77.2090);

      final incident = IncidentModel(
        id: '', // Will be generated by Firestore
        type: 'other',
        roomNumber: widget.roomNumber,
        guestId: 'guest_automated',
        authMethod: 'automated_pulse',
        description: "Automated SOS alert triggered from guest dashboard.",
        severity: 5, // Max severity for automated alerts
        status: 'received',
        closestStaffId: closestId,
        createdAt: DateTime.now(),
      );

      final newId = await firestore.createIncident(incident);

      if (mounted) {
        context.go('/status_tracking?id=$newId&type=other&room=${widget.roomNumber}');
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text("Error sending alert: $e"), backgroundColor: Colors.red),
        );
        context.pop(); // Go back if creation fails
      }
    }
  }

  void _cancelAlert() {
    _timer?.cancel();
    Vibration.cancel();
    context.pop();
  }

  @override
  void dispose() {
    _timer?.cancel();
    _pulseController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    double btnWidth = 120.0 + (_counter - 1) * 40.0;

    return Scaffold(
      backgroundColor: Colors.transparent,
      body: AnimatedBuilder(
        animation: _pulseController,
        builder: (context, child) {
          return Container(
            width: double.infinity,
            decoration: BoxDecoration(
              gradient: RadialGradient(
                center: Alignment.center,
                radius: 1.5,
                colors: [
                  Color.lerp(const Color(0xFFFF4D67), const Color(0xFFFF8599), _pulseController.value)!,
                  Color.lerp(const Color(0xFFFF8599), const Color(0xFF1A1A2E), _pulseController.value)!,
                ],
              ),
            ),
            child: child,
          );
        },
        child: SafeArea(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Spacer(),
              // Siren Icon
              Container(
                padding: const EdgeInsets.all(24),
                decoration: BoxDecoration(
                  shape: BoxShape.circle,
                  color: Colors.white.withValues(alpha: 0.1),
                ),
                child: const Icon(Icons.emergency_rounded, color: Colors.white, size: 64),
              )
              .animate(onPlay: (c) => c.repeat())
              .scale(begin: const Offset(0.8, 0.8), end: const Offset(1.2, 1.2), duration: 500.ms, curve: Curves.easeInOut)
              .then()
              .shake(hz: 10, rotation: 0.1),
              
              const SizedBox(height: 24),
              Text(
                "CRITICAL SOS TRIGGERED",
                style: AppTextStyles.heading.copyWith(
                  color: Colors.white, 
                  fontWeight: FontWeight.w900,
                  letterSpacing: 2,
                ),
              ).animate(onPlay: (c) => c.repeat()).shimmer(duration: 2.seconds),
              
              const SizedBox(height: 8),
              Text(
                "HELP IS BEING DISPATCHED TO ROOM ${widget.roomNumber}",
                style: AppTextStyles.body.copyWith(color: Colors.white.withValues(alpha: 0.8), fontWeight: FontWeight.bold),
                textAlign: TextAlign.center,
              ),
              
              const SizedBox(height: 64),
              Stack(
                alignment: Alignment.center,
                children: [
                  SizedBox(
                    width: 180,
                    height: 180,
                    child: CircularProgressIndicator(
                      value: _counter / 5.0,
                      strokeWidth: 12,
                      color: Colors.white,
                      backgroundColor: Colors.white.withValues(alpha: 0.2),
                    ),
                  ),
                  Text(
                    '$_counter',
                    key: ValueKey<int>(_counter),
                    style: AppTextStyles.display.copyWith(
                      color: Colors.white, 
                      fontSize: 100,
                      fontWeight: FontWeight.w900,
                    ),
                  ).animate(key: ValueKey(_counter)).scale(begin: const Offset(2, 2), end: const Offset(1, 1), duration: 200.ms).shake(),
                ],
              ),
              const Spacer(),
              AnimatedContainer(
                duration: const Duration(seconds: 1),
                width: btnWidth,
                height: 70,
                child: ElevatedButton(
                  onPressed: _cancelAlert,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.white,
                    foregroundColor: const Color(0xFFFF4D67),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(35)),
                    elevation: 10,
                  ),
                  child: Text(
                    "ABORT ALERT",
                    style: AppTextStyles.button.copyWith(fontWeight: FontWeight.w900, letterSpacing: 1.5),
                  ),
                ),
              ),
              const SizedBox(height: 24),
              TextButton(
                onPressed: _sendAlert,
                child: Text(
                  "CONFIRM IMMEDIATELY",
                  style: AppTextStyles.body.copyWith(
                    color: Colors.white.withValues(alpha: 0.6),
                    decoration: TextDecoration.underline,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
              const SizedBox(height: 40),
            ],
          ),
        ),
      ).animate().fadeIn(duration: 300.ms).scale(begin: const Offset(0.9, 0.9)),
    );
  }
}
